steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'compliance-api'
    args: ['ci']
  - name: "gcr.io/cloud-builders/npm"
    dir: 'compliance-api'
    args: ['test']
    env:
     - 'CHECKS_PATH=src/__tests__/testData/checks'
     - 'DEFINITIONS_URL=https://raw.githubusercontent.com/cds-snc/ITSG-33-definitions/master/ITSG-33a.yaml'
     - 'CERTIFICATION_URL=https://raw.githubusercontent.com/cds-snc/ITSG-33-baselines/master/light.yaml'
     - 'DB_URI=mongodb://'
     - 'DB_USER='
     - 'DB_PASS='
  - name: "gcr.io/cloud-builders/docker"
    id: push_docker_hub
    dir: 'compliance-api'
    entrypoint: "bash"
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then docker build -t cdssnc/compliance-api:latest . && docker login docker.io -u $$DOCKER_USERNAME -p $$DOCKER_PASSWORD && docker push cdssnc/compliance-api:latest; else exit 0; fi
    secretEnv:
      ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
secrets:
  - kmsKeyName: projects/cds-snc/locations/global/keyRings/cds-keys/cryptoKeys/platform
    secretEnv:
      DOCKER_USERNAME: CiQADcHLVsVgh3MLCKbzApGWlwEexSI2QeRfk2sLd4dWiaIO0FgSNACMLY+dy5FsylxVpjGphcUlzx6dSsh65liJemmJAul1vNkeYO8IjO8BHl7/duQNoMJhJto=
      DOCKER_PASSWORD: CiQADcHLVrNicvBVdCtT4fOem1BB4emGXf/vCgB/6NIikAbXYHoSMQCMLY+dIxPG60OWFb9hVWNWTNXUQLN/q35Uf1onCnu/2ShCURyhi0R/z9Aq6bV2Ljs=
